# fonts
font_family monospace    
bold_font auto
italic_font auto
bold_italic_font auto

font_size 16

# cursor
cursor_shape beam
cursor_text_color #505050

#colors


#background
background_opacity 0.5

# url's
url_color #00bd87
url_style curly

# window layout
remember_window_size yes
initial_window_width 640
initial_window_height 480

# other stuff
